# Generated by Django 5.1 on 2024-08-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_created_at_todo_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=128)),
                ('user_email', models.CharField(max_length=100, unique=True)),
                ('user_age', models.IntegerField(default=30)),
                ('user_avatar', models.CharField(default='empty.jpg', max_length=100)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
